theme: jekyll-theme-cayman
show_downloads: ["true"]
Github :
  zip_url : https://github.com/IMaresaLI/Proxy_Checker/blob/lastversion/dist/proxyCheck_mp-0.0.9.tar.gz 
  another_url : https://github.com/IMaresaLI/Proxy_Checker/blob/lastversion/dist/proxyCheck_mp-0.0.9-py3-none-any.whl
