theme: jekyll-theme-cayman
show_downloads: true
buttons:
  zip_url: https://github.com/IMaresaLI/Proxy_Checker/raw/lastversion/proxyCheck.zip
  zip_title: View Documentation
  zip_hide: false
  tar_hide: true
  github_hide: true
